// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: starwars.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// StarWarsServiceClient is the client API for StarWarsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StarWarsServiceClient interface {
	// simple RPC
	RandomCharacter(ctx context.Context, in *NoParam, opts ...grpc.CallOption) (*Character, error)
	// server streaming RPC
	RandomCharacterByCount(ctx context.Context, in *CharacterCount, opts ...grpc.CallOption) (StarWarsService_RandomCharacterByCountClient, error)
}

type starWarsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStarWarsServiceClient(cc grpc.ClientConnInterface) StarWarsServiceClient {
	return &starWarsServiceClient{cc}
}

func (c *starWarsServiceClient) RandomCharacter(ctx context.Context, in *NoParam, opts ...grpc.CallOption) (*Character, error) {
	out := new(Character)
	err := c.cc.Invoke(ctx, "/sw_service.StarWarsService/RandomCharacter", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *starWarsServiceClient) RandomCharacterByCount(ctx context.Context, in *CharacterCount, opts ...grpc.CallOption) (StarWarsService_RandomCharacterByCountClient, error) {
	stream, err := c.cc.NewStream(ctx, &StarWarsService_ServiceDesc.Streams[0], "/sw_service.StarWarsService/RandomCharacterByCount", opts...)
	if err != nil {
		return nil, err
	}
	x := &starWarsServiceRandomCharacterByCountClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type StarWarsService_RandomCharacterByCountClient interface {
	Recv() (*Character, error)
	grpc.ClientStream
}

type starWarsServiceRandomCharacterByCountClient struct {
	grpc.ClientStream
}

func (x *starWarsServiceRandomCharacterByCountClient) Recv() (*Character, error) {
	m := new(Character)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// StarWarsServiceServer is the server API for StarWarsService service.
// All implementations must embed UnimplementedStarWarsServiceServer
// for forward compatibility
type StarWarsServiceServer interface {
	// simple RPC
	RandomCharacter(context.Context, *NoParam) (*Character, error)
	// server streaming RPC
	RandomCharacterByCount(*CharacterCount, StarWarsService_RandomCharacterByCountServer) error
	mustEmbedUnimplementedStarWarsServiceServer()
}

// UnimplementedStarWarsServiceServer must be embedded to have forward compatible implementations.
type UnimplementedStarWarsServiceServer struct {
}

func (UnimplementedStarWarsServiceServer) RandomCharacter(context.Context, *NoParam) (*Character, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RandomCharacter not implemented")
}
func (UnimplementedStarWarsServiceServer) RandomCharacterByCount(*CharacterCount, StarWarsService_RandomCharacterByCountServer) error {
	return status.Errorf(codes.Unimplemented, "method RandomCharacterByCount not implemented")
}
func (UnimplementedStarWarsServiceServer) mustEmbedUnimplementedStarWarsServiceServer() {}

// UnsafeStarWarsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StarWarsServiceServer will
// result in compilation errors.
type UnsafeStarWarsServiceServer interface {
	mustEmbedUnimplementedStarWarsServiceServer()
}

func RegisterStarWarsServiceServer(s grpc.ServiceRegistrar, srv StarWarsServiceServer) {
	s.RegisterService(&StarWarsService_ServiceDesc, srv)
}

func _StarWarsService_RandomCharacter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NoParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StarWarsServiceServer).RandomCharacter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sw_service.StarWarsService/RandomCharacter",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StarWarsServiceServer).RandomCharacter(ctx, req.(*NoParam))
	}
	return interceptor(ctx, in, info, handler)
}

func _StarWarsService_RandomCharacterByCount_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CharacterCount)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StarWarsServiceServer).RandomCharacterByCount(m, &starWarsServiceRandomCharacterByCountServer{stream})
}

type StarWarsService_RandomCharacterByCountServer interface {
	Send(*Character) error
	grpc.ServerStream
}

type starWarsServiceRandomCharacterByCountServer struct {
	grpc.ServerStream
}

func (x *starWarsServiceRandomCharacterByCountServer) Send(m *Character) error {
	return x.ServerStream.SendMsg(m)
}

// StarWarsService_ServiceDesc is the grpc.ServiceDesc for StarWarsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StarWarsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sw_service.StarWarsService",
	HandlerType: (*StarWarsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RandomCharacter",
			Handler:    _StarWarsService_RandomCharacter_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RandomCharacterByCount",
			Handler:       _StarWarsService_RandomCharacterByCount_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "starwars.proto",
}
