// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: starwars.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// StarWarsServiceClient is the client API for StarWarsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StarWarsServiceClient interface {
	// simple RPC
	GetRandomCharacter(ctx context.Context, in *NoParam, opts ...grpc.CallOption) (*Character, error)
	// server streaming RPC
	GetSeveralRandomCharacter(ctx context.Context, in *CharacterCount, opts ...grpc.CallOption) (StarWarsService_GetSeveralRandomCharacterClient, error)
}

type starWarsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStarWarsServiceClient(cc grpc.ClientConnInterface) StarWarsServiceClient {
	return &starWarsServiceClient{cc}
}

func (c *starWarsServiceClient) GetRandomCharacter(ctx context.Context, in *NoParam, opts ...grpc.CallOption) (*Character, error) {
	out := new(Character)
	err := c.cc.Invoke(ctx, "/sw_service.StarWarsService/GetRandomCharacter", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *starWarsServiceClient) GetSeveralRandomCharacter(ctx context.Context, in *CharacterCount, opts ...grpc.CallOption) (StarWarsService_GetSeveralRandomCharacterClient, error) {
	stream, err := c.cc.NewStream(ctx, &StarWarsService_ServiceDesc.Streams[0], "/sw_service.StarWarsService/GetSeveralRandomCharacter", opts...)
	if err != nil {
		return nil, err
	}
	x := &starWarsServiceGetSeveralRandomCharacterClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type StarWarsService_GetSeveralRandomCharacterClient interface {
	Recv() (*Character, error)
	grpc.ClientStream
}

type starWarsServiceGetSeveralRandomCharacterClient struct {
	grpc.ClientStream
}

func (x *starWarsServiceGetSeveralRandomCharacterClient) Recv() (*Character, error) {
	m := new(Character)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// StarWarsServiceServer is the server API for StarWarsService service.
// All implementations must embed UnimplementedStarWarsServiceServer
// for forward compatibility
type StarWarsServiceServer interface {
	// simple RPC
	GetRandomCharacter(context.Context, *NoParam) (*Character, error)
	// server streaming RPC
	GetSeveralRandomCharacter(*CharacterCount, StarWarsService_GetSeveralRandomCharacterServer) error
	mustEmbedUnimplementedStarWarsServiceServer()
}

// UnimplementedStarWarsServiceServer must be embedded to have forward compatible implementations.
type UnimplementedStarWarsServiceServer struct {
}

func (UnimplementedStarWarsServiceServer) GetRandomCharacter(context.Context, *NoParam) (*Character, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRandomCharacter not implemented")
}
func (UnimplementedStarWarsServiceServer) GetSeveralRandomCharacter(*CharacterCount, StarWarsService_GetSeveralRandomCharacterServer) error {
	return status.Errorf(codes.Unimplemented, "method GetSeveralRandomCharacter not implemented")
}
func (UnimplementedStarWarsServiceServer) mustEmbedUnimplementedStarWarsServiceServer() {}

// UnsafeStarWarsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StarWarsServiceServer will
// result in compilation errors.
type UnsafeStarWarsServiceServer interface {
	mustEmbedUnimplementedStarWarsServiceServer()
}

func RegisterStarWarsServiceServer(s grpc.ServiceRegistrar, srv StarWarsServiceServer) {
	s.RegisterService(&StarWarsService_ServiceDesc, srv)
}

func _StarWarsService_GetRandomCharacter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NoParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StarWarsServiceServer).GetRandomCharacter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sw_service.StarWarsService/GetRandomCharacter",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StarWarsServiceServer).GetRandomCharacter(ctx, req.(*NoParam))
	}
	return interceptor(ctx, in, info, handler)
}

func _StarWarsService_GetSeveralRandomCharacter_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CharacterCount)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StarWarsServiceServer).GetSeveralRandomCharacter(m, &starWarsServiceGetSeveralRandomCharacterServer{stream})
}

type StarWarsService_GetSeveralRandomCharacterServer interface {
	Send(*Character) error
	grpc.ServerStream
}

type starWarsServiceGetSeveralRandomCharacterServer struct {
	grpc.ServerStream
}

func (x *starWarsServiceGetSeveralRandomCharacterServer) Send(m *Character) error {
	return x.ServerStream.SendMsg(m)
}

// StarWarsService_ServiceDesc is the grpc.ServiceDesc for StarWarsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StarWarsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sw_service.StarWarsService",
	HandlerType: (*StarWarsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRandomCharacter",
			Handler:    _StarWarsService_GetRandomCharacter_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetSeveralRandomCharacter",
			Handler:       _StarWarsService_GetSeveralRandomCharacter_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "starwars.proto",
}
